### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by Publictuti09** [enohka/moddingSuite#19]
When I try to launch the Suite it crashes and leaves this message, 

"System.UnauthorizedAccessException: Access to the path 'C:\Documents and Settings' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.DirectoryInfo.EnumerateDirectories()
   at moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseDirectory(DirectoryInfo info)
   at moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseDirectory(DirectoryInfo info)
   at moddingSuite.ViewModel.Edata.WorkspaceViewModel..ctor(Settings settings)
   at moddingSuite.ViewModel.Edata.EdataManagerViewModel..ctor()
   at moddingSuite.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"

**Comment by unitasu11** [comment]
same here

**Comment by enohka** [comment]
Try running it as admin in this case it should fix the problem.
