### ISSUE TITLE
Cannot open mod suite, access to 'C:\Documents and Settings' denied

### ISSUE THREAD

**Issue by Ender117** [enohka/moddingSuite#29]
System.UnauthorizedAccessException: Access to the path 'C:\Documents and Settings' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.EnumerateDirectories()
   at moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseDirectory(DirectoryInfo info)
   at moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseDirectory(DirectoryInfo info)
   at moddingSuite.ViewModel.Edata.WorkspaceViewModel..ctor(Settings settings)
   at moddingSuite.ViewModel.Edata.EdataManagerViewModel..ctor()
   at moddingSuite.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Have tried compatibility and run as admin, neither works. My guess is that "Documents and Settings" no longer exist in latest win10 installs. May be use %USERPROFILE% instead?

**Comment by perkl566** [comment]
Try a path without spaces.

**Comment by Ender117** [comment]
OK, I followed the instruction here:

https://forums.eugensystems.com/viewtopic.php?t=59645
> 1. close modding suite and go to:
> C:\Users\<your user account name>\AppData\Roaming\edataFileManager
> 
> 2. backup settings.xml somewhere else
> 3. delete settings.xml from this location
> 4. start modding suite
> 5. configure the paths correctly. Don't use something like "C:\"! If you use for instance "C:\" the modding suite tries to Parse your whole HDD and watches for changes on it. Create a DEDICATED directory somewhere as your export directory and you will be fine.

But I had to delete the %APPDATA%\edataFileManager folder instead of the xml file.
